# Generated by Django 5.2.1 on 2025-05-10 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('area', models.CharField(choices=[('Medicina General', 'Medicina General'), ('Cirugía', 'Cirugía'), ('Pediatría', 'Pediatría'), ('Cardiología', 'Cardiología'), ('Dermatología', 'Dermatología'), ('Neurología', 'Neurología')], max_length=50)),
            ],
        ),
    ]
