# Generated by Django 5.2.1 on 2025-05-10 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        ('especialidad', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorEspecialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_certificacion', models.DateField(blank=True, null=True)),
                ('nivel', models.CharField(choices=[('Junior', 'Junior'), ('Senior', 'Senior'), ('Consultor', 'Consultor')], max_length=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='especialidad.especialidad')),
            ],
            options={
                'unique_together': {('doctor', 'especialidad')},
            },
        ),
    ]
