# Generated by Django 5.2.1 on 2025-05-10 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('anios_experiencia', models.PositiveIntegerField()),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_licencia', models.CharField(max_length=50, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('horario', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
